variables:
  subscriptionId: "<subscriptionId>"
  environmentName: "prd"
  azureServiceConnection: "ucorp-devops-msdn-sp"
  rgName: "ucorp-lab-aa-rg"
  runbookName: "FormsW11UpdateRequests"
  hostnameId: "<hostnameId>"
  hybridWorkerGroup: "ucorp-lab-hg"
  automationAccountName: "ucorp-lab-aa"
  azureLocation: "westeurope"
  logicAppName: "logic-msforms-automation"
  automationConnectionDisplayName: "AutomationConnection"
  automationConnectionName: "azureautomation"
  microsoftformsConnnectionDisplayName: "AutomationConnection"
  microsoftformsConnectionName: "microsoftforms"
  microsoftFormsId: "<microsoftFormsId>"