trigger: none
pr: none

name: "$(Product).$(Major).$(Minor).$(Date:yyyMMdd)$(Rev:.r)"

variables:
  Product: AAS.Ucorp
  Major: 1
  Minor: 0
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

resources:
  repositories:
  - repository: AVD
    type: git
    name: AVD

stages:
  - stage: deploy_wvd_aib_identity
    displayName: deploy wvd aib identity
    variables:
      - template: vars/vars-aib-wvd.yml@AVD
    jobs:
    - job: deploy_wvd_aib_identity
      displayName: deploy wvd aib identity
      pool:
        vmImage: windows-2022
      steps:
      - task: AzurePowerShell@5
        displayName: Deploy wvd aib identity with ${{variables.azureServiceConnection}} on ${{variables.subscriptionName}}
        inputs:
          azureSubscription: ${{variables.azureServiceConnection}}
          ScriptType: 'InlineScript'
          Inline: |
            . "$($env:BUILD_SOURCESDIRECTORY)/functions/deploy-wvd-aib-identity.ps1"
            deploy-wvd-aib-identity `
            -armFile "$($env:BUILD_SOURCESDIRECTORY)/arm/deploy-wvd-aib-identity.json" `
            -customer $env:CUSTOMER `
            -environment $env:ENVIRONMENT `
            -solution $env:SOLUTION `
            -subscriptionName $env:SUBSCRIPTIONNAME `
            -offer $env:OFFER `
            -sku $env:SKU `
            -publisher $env:PUBLISHER `
            -generation $env:GENERATION
          azurePowerShellVersion: 'LatestVersion'